# DO NOT COMMIT THIS FILE TO YOUR REPOSITORY
# Use this file for local development only.
# For Streamlit Cloud, copy and paste the contents into the app's Secrets UI.
OPENROUTER_API_KEY = "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"